### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [fiddlerwoaroof/data-lens#3]
Building with SBCL 2.1.0.49-5491c03a5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id bd9ef2fba3ba5595e2196961b9bee11e29377e38

*data-lens* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A40103}>: no symbol named "INTO" in "DATA-LENS.TRANSDUCERS.INTERNALS"

```

*data-lens/beta/transducers* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A40103}>: no symbol named "INTO" in "DATA-LENS.TRANSDUCERS.INTERNALS"

```

*data-lens/transducers/test* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001A40103}>: no symbol named "INTO" in "DATA-LENS.TRANSDUCERS.INTERNALS"

```

[Full log here](http://report.quicklisp.org/2021-01-18/failure-report/data-lens.html)

**Comment by fiddlerwoaroof** [comment]
@quicklisp this should be fixed in c80aff0f0bc0137e229f5fbc234b08dd1aa97777
