### ISSUE TITLE
Need to ensure adjustability for vector-push-extend

### ISSUE THREAD

**Issue by Yehouda** [fiddlerwoaroof/data-lens#4]
https://github.com/fiddlerwoaroof/data-lens/blob/c80aff0f0bc0137e229f5fbc234b08dd1aa97777/transducers.lisp#L164

The stepper for vector-builder uses **vector-push-extend**. **vector-push-extend**  is documented to give an error if it needs to extend the vector and it is not adjustable: http://www.lispworks.com/documentation/HyperSpec/Body/f_vec_ps.htm
"An error of type error is signaled by vector-push-extend if it tries to extend vector and vector is not actually adjustable. "

So the builder-for-input method must ensure that the vector is adjustable.
Adding **:adjustable t** to the **make-array** call is the simplest solution.

**Comment by fiddlerwoaroof** [comment]
This is a good point. I probably should document this requirement for into. 

In the normal case (getting an array from the result of calling INIT), this is guaranteed:

https://github.com/fiddlerwoaroof/data-lens/blob/c80aff0f0bc0137e229f5fbc234b08dd1aa97777/transducers.lisp#L162-L163
