### ISSUE TITLE
Gensyms and keywords mixed in DEFPACKAGE :EXPORT

### ISSUE THREAD

**Issue by phoe** [fiddlerwoaroof/data-lens#5]
https://github.com/fiddlerwoaroof/data-lens/blob/c80aff0f0bc0137e229f5fbc234b08dd1aa97777/package.lisp#L34-L40

**Comment by fiddlerwoaroof** [comment]
I should get around to cleaning this up, The original reason was I preferred to use keywords, but emacs lines up `#:` better :)

**Comment by fiddlerwoaroof** [comment]
Done
