### ISSUE TITLE
File name too long in docs/

### ISSUE THREAD

**Issue by vindarel** [fiddlerwoaroof/data-lens#7]
Hi, I'm trying to load your cl-git, hence data-lens, and I get:

```
Error opening #P"/home/vince/quicklisp/dists/quicklisp/software/data-lens-20221106-git/docs/go-to-the-DATA_002dLENS_002eTRANSDUCERS_002eINTERNALS_005b_003f_005d_005b_003f_005dINIT-eql-DATA_002dLENS_002eTRANSDUCERS_005b_003f_005d_005b_003f_005dVECTOR_002dBUILDER-method.html":

  File name too long
   [Condition of type SB-INT:SIMPLE-FILE-ERROR]
```

The available restarts are:

```
Restarts:
 0: [CONTINUE] Retry opening.
 1: [USE-VALUE] Try opening a different file.
 2: [ABORT] Give up on "data-lens"
 3: [ABORT] Give up on "co.fwoar.cl-git"
 4: [REGISTER-LOCAL-PROJECTS] Register local projects and try again.
 5: [RETRY] Retry SLIME REPL evaluation request.
 6: [*ABORT] Return to SLIME's top level.
 7: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1007A34303}>)
```

But I couldn't find a way to ignore, accept or fix this. I don't even find where these `docs/` files are generated. Any recommendation? 

Thanks

---

on LinuxMint

**Comment by fiddlerwoaroof** [comment]
Interesting, I wonder if it's a filesystem issue.  As a quick workaround, I'd  do 

```bash
rm -rf /home/vince/quicklisp/dists/quicklisp/software/data-lens-20221106-git/docs
```

**Comment by fiddlerwoaroof** [comment]
Also, looking at that date, the version of data-lens in quicklisp might be too old: it would be a good idea, I think, to clone this repository into local-projects.  I've also removed the `docs/` directory recently, so it would solve that problem.

**Comment by vindarel** [comment]
oh of course, I cloned cl-git and didn't think about data-lens.

I think too, it is EXT3.

ps: you might want 

```diff
   (:import-from :fwoar.cl-git.commit #:git-commit)
   (:import-from :fwoar.cl-git.pack #:packed-ref)
-  (:import-from :fwoar.cl-git.ref #:loose-ref #:ref-hash #:ref-repo)
+  (:import-from :fwoar.cl-git.ref #:loose-ref #:loose-ref-file #:ref-hash #:ref-repo)
```

and fix the "show files in a commit" example where `juxt` and `component` are not defined.

thanks

**Comment by edwlan** [comment]
Cool, I'm pretty close to publishing this in quicklisp, at which point I'm hoping to have enough test coverage and documentation to make this easier to work with.

**Comment by vindarel** [comment]
Cool. This will be great. Yesterday I tried to answer questions like "get commit information from a hash" or "get latest commits" and it wasn't easy to discover. Some docstrings would already help ;)

```lisp
;; data from a commit hash:
(git:with-repository (".")
      (fwoar.cl-git:ref (git:repository) "c0d669"))

(git:component :tree :entries *)

(mapcar (lambda (it) (git:component :name it)) *)
;; ("README.md" "lem-init.lisp" "time-stamp.lisp")

;; get latest commits:
;; todo
```

(I'd like to use this lib in Lem's WIP git client, to replace direct calls to git :) )
